from .create_master_password import CreateMasterPasswordDialog
from .password_details import PasswordDetailsDialog
from .add_password import AddPasswordDialog
from .change_master_password import ChangeMasterPasswordDialog